### ISSUE TITLE
jtframe files: do not require path for .yaml files

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#356]
yaml files in the cfg require a relative path:

```
game:
  - from: flane
    get:
      - jtflane_game.v
      - ../cfg/common.yaml
```

Change it so yaml files are searched for automatically in the cfg folder of a core:

```
game:
  - from: flane
    get:
      - jtflane_game.v
      - common.yaml
```
