### ISSUE TITLE
jtframe mem: clock sections with a single output should not produce a warning

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#373]
Up to commit da37a024, this mem.yaml generates a verilator warning:

```
clocks:
  clk48:
    - freq: 4000000
      outputs:
        - cen_fm
```       

Which is fixed with:

```
clocks:
  clk48:
    - freq: 4000000
      outputs:
        - cen_fm
        - cen_nc
```

The framework should generate the not-connected wire automatically.
