### ISSUE TITLE
global audio mixer

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#402]
Define the audio output in `mem.yaml` so it gets solved with common features:

- correct resampling at 48kHz of each channel
- DC removal
- Audio monitor (debugging)
- Individual audio muting (debugging)
- channel gain can be either fixed or come from a core signal 

Example:

```
audio:
  - name: fm
    gain: 0x40
    stereo: true
    rate: 55000
  - name: pcm
    gain_ctrl: true
    rate: 150000
    stereo:  false
    dcrm: true
```
