### ISSUE TITLE
identificar filtros RC para PCM

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#562]
Escribir en el fichero cfg/mem.yaml una sección audio describiendo el filtro RC paso bajo del chip de FM. Por ejemplo, para aliens sería:

```
audio:
  - name: fm
    stereo: true
  - name: pcm
    data_width: 12
    rout: 100k
    res: 20k
    cap: 470p
```
Donde **rout** es la resistencia de salida del DAC, res la resistencia serie y **cap** el condensador a masa.

- [x] aliens
- [x] castle
- [x] comsc
- [x] cop
- [x] dd
- [x] dd2
- [x] flane
- [x] fround
- [x] kchamp
- [x] kicker
- [x] kiwi
- [x] kunio
- [x] midres
- [x] mx5k
- [x] ninja
- [x] outrun
- [x] pang
- [x] rastan
- [x] roadf
- [x] s16
- [x] s16b
- [x] sbaskt
- [x] sf
- [x] shanon
- [x] shouse
- [x] simson
- [x] tmnt
- [x] tora
- [x] track
- [x] trojan
- [x] twin16
- [x] vigil
- [x] yiear
