### ISSUE TITLE
Crime Fighters - Low drum volume

### ISSUE THREAD

**Issue by Areku-The-OF** [jotego/jtcores#910]
One of the highlights of this game is its music and for some reason the drums are barely audible compared to what I remember. I've compared it with footage from MAME, Final Burn and even real hardware and the drums sound loud and clear on those.

**Comment by jotego** [comment]
The mem.yaml description is referring to a passive adder, where rsum represents a resistor to ground:

``` YAML
audio:
  rsum: 10k
  channels:
    - {name: fm,  module: jt51,     rsum:  6.2k,  rc: [{ r:  859,   c: 33n  }, {r: 1rout, c: 2.2n }]}
    - {name: pcm, module: jt007232, rsum: 12.25k, rc: [{ r: 33k, c: 470p }], pre: 0.28 }
```
This produces the following gains in hex:

```
    .g0     ( 8'h80 ), // fm  = 1.0
    .g1     ( 8'h24 ), // pcm = 0.18
```

But in the circuit, Rsum (R9) is the feedback resistor of an opamp. So it has the opposite effect. 
![image](https://github.com/user-attachments/assets/bd1aa51b-0e74-473e-86b3-f95e286e111a)

A very recent addition to JTFRAME makes it possible to specify this behaviour by setting **rsum_feedback_res**:

``` YAML
  rsum: 10k
  rsum_feedback_res: true
  channels:
    - {name: fm,  module: jt51,     rsum:  3.2k,  rc: [{ r:  859,   c: 33n  }, {r: 1rout, c: 2.2n }]}
    - {name: pcm, module: jt007232, rsum: 13.25k, rc: [{ r: 33k, c: 470p }], pre: 0.28 }
```
Note that there are some changes to the channel rsum values too, but the critical part is the changed to feedback resistor. Now the channel gains are:

```
    .g0     ( 8'h37 ), // fm  = 0.43
    .g1     ( 8'h80 ), // pcm = 1.0
```

@rp-jt, please try the core with this change. I am not very confident about jt51's rsum=3.2k, because the two stereo outputs are connected. If the FM/PCM balance sounds off try making jt51's rsum 3.2k*2 and 3.2k/2.

Check out the schematics for the other games in the core and verify that they have the same resistor values for all components and that the analog circuit overall is identical.
